### ISSUE TITLE
Enquiry about project status and ownership

### ISSUE THREAD

**Issue by grant-zietsman** [IBM/varnish-operator#111]
First off, I am impressed with what this operator offers and the future plans look promising.

It is clear that the project is still currently in alpha status and appears that core contributions have slowed down somewhat.

Can more context be provided regarding the future of this project? Is this still something that IBM is actively developing?

cc @tomashibm @arthurzenika @cin

**Comment by arthurzenika** [comment]
Sorry, can't help you with your questions, I contributed some minor documentation changes and issues a few years ago. Hope other people can answer your questions.

**Comment by cin** [comment]
Hey @grant-zietsman, this project is currently inactive since most of us have moved on from IBM. I have been maintaining a fork of the project [here](https://github.com/cin/varnish-operator). I haven't been adding new features necessarily, but I've been updating dependencies and addressing vulnerabilities. It's actually past time for another round of updates seeing as the last release was back in April. I would like to get things merged back here at some point, but there's no guarantee that will ever happen. HTH clarify things a bit. If you have any questions, feel free to reach out either on here or my fork. Contributions are always welcome as well. :)

**Comment by grant-zietsman** [comment]
Thank you for the context @cin.
